name: "Shortest Tests"

on:
  pull_request:
    branches: [main]

jobs:
  shortest:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    env:
      ANTHROPIC_API_KEY: ${{ secrets.SHORTEST_ANTHROPIC_API_KEY }}
      CLERK_PUBLISHABLE_KEY: ${{ secrets.CLERK_PUBLISHABLE_KEY }}
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
    
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          if [ ! -f "pnpm-lock.yaml" ]; then
            pnpm install
          else
            pnpm install --frozen-lockfile
          fi

      - name: Install Playwright browsers
        run: pnpm exec playwright install

      - name: Wait for Vercel preview deployment
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.2
        id: waitFor
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 300

      - name: Run Shortest tests
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ steps.waitFor.outputs.url }}
        run: pnpm exec shortest --headless --target=${{ steps.waitFor.outputs.url }}