name: "Shortest Tests"

on:
  pull_request:
    branches: [main]

jobs:
  shortest:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    env:
      ANTHROPIC_API_KEY: ${{ secrets.SHORTEST_ANTHROPIC_API_KEY }}
      CLERK_PUBLISHABLE_KEY: ${{ secrets.CLERK_PUBLISHABLE_KEY }}
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
    
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Install Playwright browsers
        run: pnpm exec playwright install

      - name: Get Vercel preview URL
        id: vercel_preview
        uses: actions/github-script@v7
        with:
          script: |
            const deployments = await github.rest.repos.listDeployments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha
            });
            if (deployments.data.length > 0) {
              return deployments.data[0].payload.url;
            }
            throw new Error('No deployment found');

      - name: Run Shortest tests
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ steps.vercel_preview.outputs.result }}
        run: pnpm exec shortest --headless --target=${{ steps.vercel_preview.outputs.result }}